
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
        
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DEFAULT_REGION=eu-west-1
      - S3_INITIAL_BUCKETS=uploads
    volumes:
      - ./init-scripts:/etc/localstack/init/ready.d:ro
      - /localstack/data:/var/lib/localstack

volumes:
  pgdata:
